[package]
name = "quickedit"
description = "Minecraft world editor written in Rust"
version = "1.0.0"
authors = ["Earthcomputer <burtonjae@hotmail.co.uk>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
profiling = "1.0.5"
glium = "0.28.0"
winit = "0.23.0"
conrod_core = "0.76.0"
conrod_glium = "0.76.0"
conrod_winit = "0.76.0"
native-dialog = "0.6.1"
num-integer = "0.1.44"
num-traits = "0.2.14"
internment = { version = "0.5.5", features = ["arc", "serde"] }
dashmap = { git = "https://github.com/Earthcomputer/dashmap", rev = "e3de359" } # https://github.com/xacrimon/dashmap/issues/167
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt", rev = "ce60b81" }
positioned-io-preview = "0.3.3"
byteorder = "1.4.3"
lazy_static = "1.4.0"
ahash = { version = "0.7.6", features = ["serde"] }
image = { version = "0.23.14", default_features = false, features = ["png"] }
home = "0.5.3"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
serde_with = "1.11.0"
sha-1 = "0.10.0"
chrono = { version = "0.4.19", features = ["serde"] }
zip = "0.5.13"
path-slash = "0.1.4"
delegate = "0.6.1"
futures-lite = "1.12.0"
async-executor = "1.4.1"
attohttpc = "0.18.0"
structopt = "0.3.25"
rayon = "1.5.1"
glam = "0.20.2"
approx = "0.5.1"
num_cpus = "1.13.1"
tracy-client = { version = "0.12.6", optional = true }
tracy-client-sys = { version = "0.16.0", optional = true }

[patch.crates-io]
tracy-client-sys = { git = "https://github.com/Earthcomputer/rust_tracy_client" }

[features]
profile-with-tracy = ["tracy-client", "tracy-client-sys", "profiling/profile-with-tracy"]

[build-dependencies]
winres = "0.1.12"
gl_generator = "0.14.0"

[package.metadata.bundle]
identifier = "net.earthcomputer.quickedit"
icon = ["res/icon_16x16.png",
    "res/icon_32x32.png",
    "res/icon_128x128.png",
    "res/icon_256x256.png",
    "res/icon_16x16@2x.png",
    "res/icon_32x32@2x.png",
    "res/icon_128x128@2x.png"
]
