on:
  - push
  - pull_request

name: Check

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: earthcomputer/rust-with-libxcb-extensions:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build