on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
  ubuntu:
    name: Build for ubuntu
    runs-on: ubuntu-latest
    container: earthcomputer/rust-with-libxcb-extensions:latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: '-C link-arg=-s'
        with:
          command: build
          args: --release
      - id: upload-release-asset
        uses: Earthcomputer/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./target/release/mcedit_rs
          asset_name: mcedit_rs_linux
          asset_content_type: application/octet-stream
  windows:
    name: Build for windows
    runs-on: windows-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: .\target\release\mcedit_rs.exe
          asset_name: mcedit_rs_windows.exe
          asset_content_type: application/octet-stream
  macos:
    name: Build for macos
    runs-on: macos-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - id: upload-release-asset
        uses: Earthcomputer/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./target/release/mcedit_rs
          asset_name: mcedit_rs_macos
          asset_content_type: application/octet-stream